#!/usr/bin/env groovy

echo("hello jenkins pipeline world!!!")

pipeline {
    agent any

    stages {
        stage('test install') {
            steps {
                script {
                    sh "apt-get -y install python3-pip"
                    sh "pip3 install awscli"
                }
            }
        }
    }
}