#!/usr/bin/env groovy

pipeline {
    agent any

    environment {
        GAME_BUILD_SCRIPT_DIR = "${env.WORKSPACE}/pipeline/buildjob"
    }
    stages {
        stage('Find Latest Ubuntu') {
            steps {
                script {
                    dir (GAME_BUILD_SCRIPT_DIR) {
                        getNextBuildJob("config.yml", "base", [])
                    }
                }
            }
        }
    }
}