#!/usr/bin/env groovy

pipeline {
    agent any

    parameters {
        choice(name: 'BUILD_JOB',
        choices: getBuildJobChoices(),
        description: 'The name of build job.')
    }
    environment {
        GAME_BUILD_SCRIPT_DIR = "${env.WORKSPACE}/pipeline/buildjob"
    }
    stages {
        stage('Find Latest Ubuntu') {
            steps {
                script {
                    dir (GAME_BUILD_SCRIPT_DIR) {
                        getNextBuildJob("config.yml", params.BUILD_JOB.split(',').collect {it.trim()})
                    }
                }
            }
        }
    }
}