#!/usr/bin/env groovy

pipeline {
    agent any

    stages {
        stage('Find Latest Ubuntu') {
            steps {
                script {
                    getNextBulildJob("config.yml", "base", [])
                }
            }
        }
    }
}